base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),

    # Web Socket
    path("ws/", include(websocket_urlpatterns)),

    # Change Password
    path('user/change-password/', auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',
         success_url='/user/password-reset-complete/'), name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path('reset_password/', auth_views.PasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='feed'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('groups/', views.groups, name='groups'),
    path('create-group/', views.create_group, name='create-group'),
    path('group-index/<slug:slug>/', views.group_index, name='group-index'),
    path('join-group/<slug:slug>/', views.join_group, name='join-group'),
    path('unfollow-group/<slug:slug>/',
         views.unfollow_group, name='unfollow-group'),
    path('photos/', views.photos, name='photos'),

    # Chat
    path('core/inbox/', views.inbox, name='inbox'),
    path('core/inbox/<username>/', views.inbox_detail, name='inbox_detail'),

    # Group Chat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/create-groupchat/", views.create_groupchat, name="create-groupchat"),
    path("core/group-inbox/<slug:slug>/",
         views.group_inbox_detail, name="group_inbox_detail"),

    # Join & leave Group Chat
    path("core/join-group-page/<slug:slug>/",
         views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/",
         views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/",
         views.leave_group_chat, name="leave_group_chat"),

    # Search
    path('search/', views.search_users, name='search_users'),

    # Games
    path("all-games/", views.games, name="games"),
    path("stack_brick/", views.stack_brick, name="stack_brick"),
    path("snake/", views.snake, name="snake"),

    # Load more post
    path('load_more_posts/', views.load_more_posts, name='load_more_posts'),




    # Ajax URLs
    path('create-post/', views.create_post, name='create-post'),
    path('like-post/', views.like_post, name='like-post'),
    path('comment-post/', views.comment_on_post, name='comment-post'),
    path('delete-post/', views.delete_post, name='delete-post'),
    path('like-comment/', views.like_comment, name='like-comment'),
    path('reply-comment/', views.reply_comment, name='reply-comment'),
    path('delete-comment/', views.delete_comment, name='delete-comment'),
    path('delete-reply/', views.delete_reply, name='delete-reply'),

    path('create-group-post/', views.create_group_post, name='create-group-post'),
    path('like-group-post/', views.like_group_post, name='like-group-post'),
    path('comment-group-post/', views.comment_on_group_post,
         name='comment-group-post'),
    path('delete-group-post/', views.delete_group_post, name='delete-group-post'),
    path('like-group-post-comment/', views.like_group_post_comment,
         name='like-group-post-comment'),
    path('reply-group-post-comment/', views.reply_group_post_comment,
         name='reply-group-post-comment'),
    path('delete-group-post-comment/', views.delete_group_post_comment,
         name='delete-group-post-comment'),
    path('delete-group-post-reply/', views.delete_group_post_reply,
         name='delete-group-post-reply'),

    path('add-friend/', views.add_friend, name='add-friend'),
    path('unfriend/', views.unfriend, name='unfriend'),
    path('accept-friend-request/', views.accept_friend_request,
         name='accept-friend-request'),
    path('reject-friend-request/', views.reject_friend_request,
         name='reject-friend-request'),
    path('block-user/', views.block_user, name='block-user'),
    path('update-notification/', views.update_notification_status,
         name='update-notification'),
    path('mark-as-read-all/', views.mark_as_read_all, name='mark-as-read-all'),

    path('create-group-post/', views.create_group_post, name='create-group-post'),

]

userauths/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.RegisterView, name='sign-up'),
    path('sign-in/', views.LoginView, name='sign-in'),
    path('logout/', views.LogoutView, name='logout'),

    path('my-profile/', views.my_profile, name='my-profile'),
    path('profile/<username>', views.friend_profile, name='profile'),

    path("profile-update/", views.profile_update, name="profile-update"),
    path("delete-user/", views.delete_user, name="delete-user"),

    # Tabs
    path("friends-tab/", views.friends_tab, name="friends-tab"),

]

templates/partials/chats_dropdown.html
{% load static %}

<div uk-toggle="target: #offcanvas-chat" class="start-chat">
    <svg class="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path>
    </svg>
</div>

<div id="offcanvas-chat" uk-offcanvas="flip: true; overlay: true">
    <div class="uk-offcanvas-bar bg-white p-0 w-full lg:w-80 shadow-2xl">


        <div class="relative pt-5 px-4">

            <h3 class="text-2xl font-bold mb-2"> Chats </h3>

            <div class="absolute right-3 top-4 flex items-center space-x-2">

                <button class="uk-offcanvas-close  px-2 -mt-1 relative rounded-full inset-0 lg:hidden blcok" type="button" uk-close></button>

                <a href="#" uk-toggle="target: #search;animation: uk-animation-slide-top-small">
                    <ion-icon name="search" class="text-xl hover:bg-gray-100 p-1 rounded-full"></ion-icon>
                </a>
                <a href="#">
                    <ion-icon name="settings-outline" class="text-xl hover:bg-gray-100 p-1 rounded-full"></ion-icon>
                </a>
                <a href="#">
                    <ion-icon name="ellipsis-vertical" class="text-xl hover:bg-gray-100 p-1 rounded-full"></ion-icon>
                </a>
                <div class="bg-white w-56 shadow-md mx-auto p-2 mt-12 rounded-md text-gray-500 hidden border border-gray-100 dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700" uk-drop="mode: click;pos: bottom-right;animation: uk-animation-slide-bottom-small; offset:5">
                    <ul class="space-y-1">
                        <li>
                            <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                <ion-icon name="checkbox-outline" class="pr-2 text-xl"></ion-icon> Mark all as read
                            </a>
                        </li>
                        <li>
                            <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                <ion-icon name="settings-outline" class="pr-2 text-xl"></ion-icon> Chat setting
                            </a>
                        </li>
                        <li>
                            <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                <ion-icon name="notifications-off-outline" class="pr-2 text-lg"></ion-icon> Disable notifications
                            </a>
                        </li>
                        <li>
                            <a href="#" class="flex items-center px-3 py-2 hover:bg-gray-100 hover:text-gray-800 rounded-md dark:hover:bg-gray-800">
                                <ion-icon name="star-outline" class="pr-2 text-xl"></ion-icon> Create a group chat
                            </a>
                        </li>
                    </ul>
                </div>


            </div>


        </div>

        <div class="absolute bg-white z-10 w-full -mt-5 lg:-mt-2 transform translate-y-1.5 py-2 border-b items-center flex" id="search" hidden>
            <input type="text" placeholder="Search.." class="flex-1">
            <ion-icon name="close-outline" class="text-2xl hover:bg-gray-100 p-1 rounded-full mr-4 cursor-pointer" uk-toggle="target: #search;animation: uk-animation-slide-top-small"></ion-icon>
        </div>

        <nav class="responsive-nav border-b extanded mb-2 -mt-2">
            <ul uk-switcher="connect: #chats-tab; animation: uk-animation-fade">
                <li class="uk-active"><a class="active" href="#0"> Friends </a></li>
                <li><a href="#0">Group Chats </a></li>
            </ul>
        </nav>

        <div class="contact-list px-2 uk-switcher" id="chats-tab">

            <div class="p-1">
                {% for friend in request.user.profile.friends.all %}
                <a href="{% url "core:inbox_detail" username=friend.username  %}">
                    <div class="contact-avatar">
                        <img src="{{ friend.profile.image.url }}" alt="">
                    </div>
                    <div class="contact-username"> {{ friend.profile.full_name }}</div>
                </a>
                {% endfor %}
                


            </div>
            <div class="p-1">
                {% for message in groupchat %}
                <a href="{% url 'core:group_inbox_detail' message.slug %}">
                    <div class="contact-avatar">
                        <img src="{{message.images.url}}" alt="">
                    </div>
                    <div class="contact-username"> {{message.name}}</div>
                </a>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

templates/partials/create-post.html
<div id="create-post-modal" class="create-post is-story" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical rounded-lg p-0 lg:w-5/12 relative shadow-2xl uk-animation-slide-bottom-small">

        <form id="post-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="text-center py-3 border-b">
                <h3 class="text-lg font-semibold"> Create Post </h3>
                <button class="uk-modal-close-default bg-gray-100 rounded-full p-2.5 right-2" type="button" uk-close uk-tooltip="title: Close ; pos: bottom ;offset:7"></button>
            </div>

            <div class="flex flex-1 items-start space-x-4 p-5">
                <img src="{{ request.user.profile.image.url }}" class="bg-gray-200 border border-white rounded-full w-11 h-11">
                <div class="flex-1 pt-2">
                    <textarea name="post-caption" id="post-caption" class="uk-textare text-black shadow-none focus:shadow-none text-xl font-medium resize-none" rows="5" placeholder="What's on your mind {{request.user|title}}?"></textarea>
                </div>

            </div>

            <div class="flex flex-1 p-5 w-100">
                <div class="flex-1 pt-2">
                    <img src="https://www.survivorsuk.org/wp-content/uploads/2017/01/no-image.jpg" id="preview_post_thumbnail" style="width: 100%; height: 200px; object-fit: cover; border-redius: 10px;" alt="" for="post-thumbnail">
                </div>
            </div>

            

            <div class="bsolute bottom-0 p-4 space-x-4 w-full">
                <div class="flex bg-gray-50 border border-purple-100 rounded-2xl p-2 shadow-sm items-center">
                    <div class="lg:block hidden ml-1"> Add to your post </div>
                    <div class="flex flex-1 items-center lg:justify-end justify-center space-x-2">

                        <label for="post-thumbnail" class="m-0">
                            <svg class="bg-blue-100 h-9 p-1.5 rounded-full text-blue-600 w-9 cursor-pointer" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                        </label>
                        <input onchange="loadFile(event)" type="file" class="d-none" name="post-thumbnail" id="post-thumbnail">
                        

                    </div>
                </div>
            </div>

            <div class="flex items-center w-full justify-between border-t p-3">

                <select class="selectpicker mt-2 story" id="visibility">
                    <option value="Everyone">Everyone</option>
                    <option value="Only me">Only me</option>
                </select>

                <div class="flex space-x-2">
                    <button type="submit" class="bg-blue-600 flex h-9 items-center justify-center rounded-md text-white px-5 font-medium">
                    Share </button>
                </div>

                <a href="#" hidden class="bg-blue-600 flex h-9 items-center justify-center rounded-lg text-white px-12 font-semibold">
                    Share </a>
            </div>
        </form>

    </div>
</div>


<script>
    var loadFile = function(event){
        var output2 = document.getElementById("preview_post_thumbnail")
        output2.src = URL.createObjectURL(event.target.files[0])
        output2.onload = function(){
            URL.createObjectURL(output2.src)
        }
    }
</script>

templates/partials/right-sidebar.html
<div class="w-full space-y-6">

    <div class="widget card p-5">
        <h4 class="text-lg font-semibold"> About </h4>
        <ul class="text-gray-600 space-y-3 mt-3">
            <li class="flex items-center space-x-2">
                <ion-icon name="home-sharp" class="rounded-full bg-gray-200 text-xl p-1 mr-3"></ion-icon>
                Live In <strong> {{ profile.address }}  </strong>
            </li>
            <li class="flex items-center space-x-2">
                <ion-icon name="globe" class="rounded-full bg-gray-200 text-xl p-1 mr-3"></ion-icon>
                From <strong> {{ profile.city}}, {{ profile.country}}  </strong>
            </li>
            <li class="flex items-center space-x-2">
                <ion-icon name="heart-sharp" class="rounded-full bg-gray-200 text-xl p-1 mr-3"></ion-icon>
                <strong style="margin-left: 0">{{ profile.relationship}}</strong>
            </li>
            <li class="flex items-center space-x-2">
                <ion-icon name="logo-rss" class="rounded-full bg-gray-200 text-xl p-1 mr-3"></ion-icon>
                Friends with<strong>{{ profile.friends.count}} People </strong>
            </li>
        </ul>

        {% if request.user == profile.user %}
        <a href="{% url "userauths:profile-update" %}" class="button gray mt-3 w-full"> Edit </a>
        {% endif %}
    </div>

    <div class="widget card p-5 border-t">
        <div class="flex items-center justify-between mb-4">
            <div>
                <h4 class="text-lg font-semibold"> Friends </h4>
                <p class="text-sm"> {{ profile.friends.all.count }} Friends</p>
            </div>
            <a href="#" class="text-blue-600" onclick="showFriends()" uk-switcher-item="1">See all</a>
        </div>
        <div class="grid grid-cols-3 gap-3 text-gray-600 font-semibold">
            {% for friend in profile.friends.all %}
            <a href="{% url "userauths:profile" friend.username %}">
                <div class="avatar relative rounded-md overflow-hidden w-full h-24 mb-2">
                    <img src="{{ friend.profile.image.url }}" alt="" class="w-full h-full object-cover absolute">
                </div>
                <div class="text-sm truncate" style="text-align: center;"> {{ friend.profile.full_name }} </div>
            </a>
            {% endfor %}
            
        </div>
        <a href="#" class="button gray mt-3 w-full" onclick="showFriends()" uk-switcher-item="1">  See all </a>
    </div>

    <!-- Groups List-->
    <div class="widget card p-5 border-t">
        <div class="flex items-center justify-between mb-2">
            <div>
                <h4 class="text-lg font-semibold"> Groups </h4>
            </div>
            <a href="{% url "core:groups" %}" class="text-blue-600 "> See all</a>
        </div>
        <div>

            {% for group in groups %}
                {% if profile.user in group.members.all and group.visibility == "Everyone" %}

                    <div class="flex items-center space-x-4 rounded-md -mx-2 p-2 hover:bg-gray-50">
                        <a href="timeline-group.html" class="w-12 h-12 flex-shrink-0 overflow-hidden rounded-full relative">
                            <img src="{{ group.image.url }}" class="absolute w-full h-full inset-0 " alt="">
                        </a>
                        <div class="flex-1">
                            <a href="timeline-page.html" class="text-base font-semibold capitalize"> {{ group.name }}  </a>
                            <div class="text-sm text-gray-500 mt-0.5"> {{ group.members.all.count }} Followers</div>
                        </div>
                        <a href="{% url "core:group-index" group.slug %}" class="flex items-center justify-center h-8 px-3 rounded-md text-sm border font-semibold bg-blue-500 text-white">
                            View
                        </a>
                    </div>
                {% endif %}
            {% endfor %}
            

        </div>
    </div>
    <!-- Groups List End-->


</div>

templates/partials/settings_sidebar.html
<div class="lg:w-1/3">
    <nav class="responsive-nav setting-nav setting-menu"
        uk-sticky="top:30 ; offset:80 ; media:@m ;bottom:true; animation: uk-animation-slide-top">
        <h4 class="mb-0 p-3 uk-visible@m hidden"> Setting Navigation </h4>
        <ul>
            <li class="{% if request.path == '/user/profile-update/' %}uk-active{% endif %}"><a href="{% url 'userauths:profile-update' %}"> <i class="uil-cog"></i> General </a></li>
            <li class="{% if request.path == '/user/change-password/' or request.path == '/user/password-reset-complete/' %}uk-active{% endif %}"><a href="{% url 'change_password' %}"> <i class="uil-unlock-alt"></i> Password </a></li>
            <li><a href="#"> <i class="uil-shield-check"></i> Security</a></li>
            <!-- <li><a href="#"> <i class="uil-bolt"></i> Membership</a></li> -->
            <!-- <li><a href="#"> <i class="uil-history"></i> Manage Sessions</a></li> -->
            <li class="{% if request.path == '/user/delete-user/'%}uk-active{% endif %}"><a href="{% url 'userauths:delete-user' %}"><i class="uil-trash-alt"></i> Delete account</a></li>
        </ul>
    </nav>
</div>