base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),

    # Web Socket
    path("ws/", include(websocket_urlpatterns)),

    # Change Password
    path('user/change-password/', auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',
         success_url='/user/password-reset-complete/'), name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path('reset_password/', auth_views.PasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='feed'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('groups/', views.groups, name='groups'),
    path('create-group/', views.create_group, name='create-group'),
    path('group-index/<slug:slug>/', views.group_index, name='group-index'),
    path('join-group/<slug:slug>/', views.join_group, name='join-group'),
    path('unfollow-group/<slug:slug>/',
         views.unfollow_group, name='unfollow-group'),
    path('photos/', views.photos, name='photos'),

    # Chat
    path('core/inbox/', views.inbox, name='inbox'),
    path('core/inbox/<username>/', views.inbox_detail, name='inbox_detail'),

    # Group Chat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/create-groupchat/", views.create_groupchat, name="create-groupchat"),
    path("core/group-inbox/<slug:slug>/",
         views.group_inbox_detail, name="group_inbox_detail"),

    # Join & leave Group Chat
    path("core/join-group-page/<slug:slug>/",
         views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/",
         views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/",
         views.leave_group_chat, name="leave_group_chat"),

    # Search
    path('search/', views.search_users, name='search_users'),

    # Games
    path("all-games/", views.games, name="games"),
    path("stack_brick/", views.stack_brick, name="stack_brick"),
    path("snake/", views.snake, name="snake"),

    # Load more post
    path('load_more_posts/', views.load_more_posts, name='load_more_posts'),




    # Ajax URLs
    path('create-post/', views.create_post, name='create-post'),
    path('like-post/', views.like_post, name='like-post'),
    path('comment-post/', views.comment_on_post, name='comment-post'),
    path('delete-post/', views.delete_post, name='delete-post'),
    path('like-comment/', views.like_comment, name='like-comment'),
    path('reply-comment/', views.reply_comment, name='reply-comment'),
    path('delete-comment/', views.delete_comment, name='delete-comment'),
    path('delete-reply/', views.delete_reply, name='delete-reply'),

    path('create-group-post/', views.create_group_post, name='create-group-post'),
    path('like-group-post/', views.like_group_post, name='like-group-post'),
    path('comment-group-post/', views.comment_on_group_post,
         name='comment-group-post'),
    path('delete-group-post/', views.delete_group_post, name='delete-group-post'),
    path('like-group-post-comment/', views.like_group_post_comment,
         name='like-group-post-comment'),
    path('reply-group-post-comment/', views.reply_group_post_comment,
         name='reply-group-post-comment'),
    path('delete-group-post-comment/', views.delete_group_post_comment,
         name='delete-group-post-comment'),
    path('delete-group-post-reply/', views.delete_group_post_reply,
         name='delete-group-post-reply'),

    path('add-friend/', views.add_friend, name='add-friend'),
    path('unfriend/', views.unfriend, name='unfriend'),
    path('accept-friend-request/', views.accept_friend_request,
         name='accept-friend-request'),
    path('reject-friend-request/', views.reject_friend_request,
         name='reject-friend-request'),
    path('block-user/', views.block_user, name='block-user'),
    path('update-notification/', views.update_notification_status,
         name='update-notification'),
    path('mark-as-read-all/', views.mark_as_read_all, name='mark-as-read-all'),

    path('create-group-post/', views.create_group_post, name='create-group-post'),

]

userauths/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.RegisterView, name='sign-up'),
    path('sign-in/', views.LoginView, name='sign-in'),
    path('logout/', views.LogoutView, name='logout'),

    path('my-profile/', views.my_profile, name='my-profile'),
    path('profile/<username>', views.friend_profile, name='profile'),

    path("profile-update/", views.profile_update, name="profile-update"),
    path("delete-user/", views.delete_user, name="delete-user"),

    # Tabs
    path("friends-tab/", views.friends_tab, name="friends-tab"),

]

core/forms.py
from django import forms
from core.models import Group, GroupChat
from userauths.models import User


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'description']


class GroupChatForm(forms.ModelForm):
    class Meta:
        model = GroupChat
        fields = ['name', 'description', 'images']

core/views.py
from django.urls import reverse
import shortuuid
import markdown


from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import OuterRef, Subquery, Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify
from django.utils.timesince import timesince
from django.views.decorators.csrf import csrf_exempt
from itertools import chain

from core.forms import GroupChatForm, GroupForm
from core.models import GroupPost, GroupPostComment, Post, Comment, ReplyComment, Friend, FriendRequest, Notification, ChatMessage, GroupChatMessage, GroupChat, Group, ReplyGroupPostComment
from userauths.models import User, Profile


# Notification Keys
noti_new_like = "New Like"
noti_new_follower = "New Follower"
noti_friend_request = "Friend Request"
noti_new_comment = "New Comment"
noti_comment_liked = "Comment Liked"
noti_comment_replied = "Comment Replied"
noti_friend_request_accepted = "Friend Request Accepted"


# Index Functions
@login_required
def index(request):
    posts = Post.objects.filter(
        active=True, visibility="Everyone").order_by("-id")
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    user = request.user
    user_groups = Group.objects.filter(members=user)

    groupchat = GroupChat.objects.filter(
        members=user, active=True)

    if user_groups.exists():
        only_me_groups = user_groups.filter(visibility="Only me")
        everyone_groups = user_groups.filter(visibility="Everyone")
        all_everyone_groups = Group.objects.filter(
            active=True, visibility="Everyone")
        groups = list(
            chain(only_me_groups, everyone_groups, all_everyone_groups))
    else:
        groups = Group.objects.filter(
            active=True, visibility="Everyone").order_by("-id")

    unique_groups = set(groups)

    context = {
        "posts": posts,
        "groups": unique_groups,
        "groupchat": groupchat
    }
    return render(request, 'core/index.html', context)


@login_required
def post_detail(request, slug):
    post = Post.objects.get(slug=slug, active=True, visibility="Everyone")
    user = request.user
    user_groups = Group.objects.filter(members=user)

    groupchat = GroupChat.objects.filter(
        members=user, active=True)

    if user_groups.exists():
        only_me_groups = user_groups.filter(visibility="Only me")
        everyone_groups = user_groups.filter(visibility="Everyone")
        all_everyone_groups = Group.objects.filter(
            active=True, visibility="Everyone")
        groups = list(
            chain(only_me_groups, everyone_groups, all_everyone_groups))
    else:
        groups = Group.objects.filter(
            active=True, visibility="Everyone").order_by("-id")

    unique_groups = set(groups)

    context = {
        "post": post,
        "groups": unique_groups,
        "groupchat": groupchat,
    }
    return render(request, 'core/post_detail.html', context)


@csrf_exempt
def create_post(request):

    if request.method == "POST":
        title = request.POST.get("post-caption")
        visibility = request.POST.get("visibility")
        image = request.FILES.get("post-thumbnail")

        if title or image:
            uuid_key = shortuuid.uuid()
            uniqueid = uuid_key[:4]

            post = Post(
                title=title,
                visibility=visibility,
                image=image,
                user=request.user,
                slug=slugify(title)[:25] + '-' + str(uniqueid.lower())
            )
            post.save()

            return JsonResponse({"post": {
                "title": post.title,
                "image": post.image.url if post.image else None,
                "full_name": post.user.profile.full_name,
                "profile_image": post.user.profile.image.url,
                "date": timesince(post.date),
                "id": post.id,
            }
            })
    return JsonResponse({"data": "sent"})


def like_post(request):
    id = request.GET['id']
    post = Post.objects.get(id=id)
    user = request.user
    bool = False

    if user in post.likes.all():
        post.likes.remove(user)
        bool = False
    else:
        post.likes.add(user)
        bool = True

        if post.user != request.user:
            send_notification(post.user, user, post, None, noti_new_like)

    data = {
        "bool": bool,
        "likes": post.likes.all().count()
    }
    return JsonResponse({"data": data})


def comment_on_post(request):
    id = request.GET['id']
    comment = request.GET['comment']
    post = Post.objects.get(id=id)
    comment_count = Comment.objects.filter(post=post).count()
    user = request.user

    new_comment = Comment.objects.create(
        post=post,
        comment=comment,
        user=user,
    )

    if new_comment.user != post.user:
        send_notification(post.user, user, post, new_comment, noti_new_comment)

    data = {
        "bool": True,
        "comment": new_comment.comment,
        "profile_image": new_comment.user.profile.image.url,
        "date": timesince(new_comment.date),
        "comment_id": new_comment.id,
        "post_id": new_comment.post.id,
        "comment_count": comment_count + int(1),
    }

    return JsonResponse({"data": data})


def like_comment(request):
    id = request.GET['id']
    comment = Comment.objects.get(id=id)
    user = request.user
    bool = False

    if user in comment.likes.all():
        comment.likes.remove(user)
        bool = False
    else:
        comment.likes.add(user)
        bool = True

        if comment.user != user:
            send_notification(comment.user, user, comment.post,
                              comment, noti_comment_liked)

    data = {
        "bool": bool,
        "likes": comment.likes.all().count()
    }
    return JsonResponse({"data": data})


def reply_comment(request):
    id = request.GET['id']
    reply = request.GET['reply']

    comment = Comment.objects.get(id=id)
    user = request.user

    new_reply = ReplyComment.objects.create(
        reply=reply,
        comment=comment,
        user=user,
    )

    data = {
        "bool": True,
        "reply": new_reply.reply,
        "profile_image": new_reply.user.profile.image.url,
        "date": timesince(new_reply.date),
        "reply_id": new_reply.id,
        "post_id": new_reply.comment.post.id,
    }

    if comment.user != user:
        send_notification(comment.user, user, comment.post,
                          comment, noti_comment_replied)

    return JsonResponse({"data": data})


def delete_comment(request):
    id = request.GET['id']
    comment = Comment.objects.get(id=id)
    comment.delete()

    data = {
        "bool": True
    }
    return JsonResponse({"data": data})


def delete_reply(request):
    id = request.GET['id']
    reply = ReplyComment.objects.get(id=id)
    reply.delete()

    data = {
        "bool": True
    }
    return JsonResponse({"data": data})


def delete_post(request):
    id = request.GET['id']
    post = Post.objects.get(id=id)
    post.delete()

    data = {
        "bool": True
    }
    return JsonResponse({"data": data})


# Group Functions
def groups(request):
    user = request.user
    user_groups = Group.objects.filter(members=user)

    groupchat = GroupChat.objects.filter(
        members=user, active=True)

    if user_groups.exists():
        only_me_groups = user_groups.filter(visibility="Only me")
        everyone_groups = user_groups.filter(visibility="Everyone")
        all_everyone_groups = Group.objects.filter(
            active=True, visibility="Everyone")
        groups = list(
            chain(only_me_groups, everyone_groups, all_everyone_groups))
    else:
        groups = Group.objects.filter(
            active=True, visibility="Everyone").order_by("-id")

    unique_groups = set(groups)

    max_members = max(unique_groups, key=lambda group: group.members.all(
    ).count()).members.all().count() if unique_groups else 0

    context = {
        "groups": unique_groups,
        "max_members": max_members,
        "groupchat": groupchat,
    }
    return render(request, 'core/groups.html', context)


def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST, request.FILES)

        if form.is_valid():
            name = request.POST.get("group-caption")
            description = request.POST.get("group-description")
            image = request.FILES.get(
                "group-thumbnail", default='noimage.gif')
            visibility = request.POST.get("group-visibility")
            website = request.POST.get("group-website")

            uuid_key = shortuuid.uuid()
            uniqueid = uuid_key[:4]
            slug = slugify(name) + '-' + str(uniqueid.lower())

            group = Group(
                user=request.user,
                name=name,
                description=description,
                website=website,
                image=image,
                slug=slug,
                visibility=visibility
            )
            group.save()
            group.members.add(request.user)
            return redirect('core:group-index', slug=group.slug)
    else:
        form = GroupForm()

    groupchat = GroupChat.objects.filter(
        members=request.user, active=True)

    return render(request, 'core/create-group.html', {'form': form, "groupchat": groupchat})


def group_index(request, slug):

templates/core/group-index.html
{% extends "partials/base.html" %}
{% load static %}
{% load mathfilters %}

{% block content %}

        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <div class="profile is_group">

                    <div class="profiles_banner">
                        <img src="{{ group.image.url }}" alt="">
                    </div>
                    <div class="profiles_content">

                        <div class="profile_info">
                            <h1> {{ group.name }} </h1>
                            <p> {{ group.visibility }} ·  {{ group.members.all.count }} member(s)</p>
                        </div>
                        <div class="flex items-center space-x-4">
                            <div class="flex items-center -space-x-4">
                                {% for icon in group.members.all|slice:"5" %}
                                <img alt="Image placeholder" src="{{ icon.profile.image.url }}" class="border-2 border-white rounded-full w-7">
                                {% endfor %}
                            </div>
                        
                            <form method="POST" action="{% url 'core:join-group' group.slug %}">
                                {% csrf_token %}
                                {% if request.user in group.members.all %}
                                    <button href="{% url 'core:unfollow-group' group.slug %}" class="unfollow-group-btn flex items-center justify-center h-9 px-5 rounded-md bg-gray-300 text-black  space-x-1.5">
                                        <span> Unfollow </span>
                                    </button>
                                
                                {% else %}
                                    <button href="{% url 'core:join-group' group.slug %}" class="unfollow-group-btn flex items-center justify-center h-9 px-5 rounded-md bg-blue-600 text-white  space-x-1.5">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5">
                                            <path fill-rule="evenodd"
                                                d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z"
                                                clip-rule="evenodd"></path>
                                        </svg>
                                        <span> Join </span>
                                    </button>
                                {% endif %}
                            </form>
                        </div>

                    </div>


                    

                </div>
                    
                <div class="md:flex md:space-x-6 lg:mx-16">
                    <div class="space-y-5 flex-shrink-0 md:w-7/12">

                        <!-- create post  -->
                        <div class="card lg:mx-0 p-4" uk-toggle="target: #create-post-modal">
                            <div class="flex space-x-3">
                                <img src="{{ request.user.profile.image.url }}" class="w-10 h-10 rounded-full">
                                <input placeholder="What's on your mind {{request.user|title}}?" class="bg-gray-100 hover:bg-gray-200 flex-1 h-10 px-6 rounded-full"> 
                            </div>
                            <div class="grid grid-flow-col pt-3 -mx-1 -mb-1 font-semibold text-sm">
                            </div> 
                        </div>
                
                        <!-- Posts -->
                        {% include "partials/group_posts.html" %}
                        <!-- Posts End-->
                        
                
                    </div>
                    <div class="w-full flex-shirink-0">

                        <div class="card p-4 mb-5">

                            <h1 class="block text-lg font-bold"> About  </h1>

                            <div class="space-y-4 mt-3">
                                
                                <div class="flex items-center space-x-3">
                                    <ion-icon name="people" class="bg-gray-100 p-2 rounded-full text-2xl" role="img" aria-label="people"></ion-icon>
                                    <div class="flex-1">
                                        <div class="font-semibold">  {{ group.members.all.count }} Member(s) </div>
                                    </div>
                                </div>
                                <div class="flex items-start space-x-3">
                                    <ion-icon name="globe-outline" class="bg-gray-100 p-2 rounded-full text-2xl" role="img" aria-label="people"></ion-icon>
                                    <div class="flex-1">
                                        <div class="font-bold"> {{ group.visibility }} </div>
                                        <div> Anyone can see who's in the group and what they post. </div>
                                    </div>
                                </div>
                                {% if group.website %}
                                    <div class="flex items-center space-x-3">
                                        <ion-icon name="unlink" class="bg-gray-100 p-1.5 rounded-full text-xl"></ion-icon>
                                        <div class="flex-1">
                                            <div>  <a href="{{group.website}}" class="text-blue-500" target="_blank"> {{ group.website }} </a> </div> 
                                        </div>
                                    </div>
                                {% endif %}

                            </div>
                            
                        </div>
                        
                        <div class="widget card p-5 border-t">
                            <div class="flex items-center justify-between mb-2">
                                <div>
                                    <h4 class="text-lg font-semibold"> Groups </h4>
                                </div>
                                <a href="{% url "core:groups" %}" class="text-blue-600 "> See all</a>
                            </div>
                            <div>
                            {% for group in groups|slice:"5" %}
                                <div class="flex items-center space-x-4 rounded-md -mx-2 p-2 hover:bg-gray-50">
                                    <a href="{% url "core:group_inbox_detail" group.slug %}" class="w-12 h-12 flex-shrink-0 overflow-hidden rounded-full relative">
                                        <img src="{{ group.image.url }}" class="absolute w-full h-full inset-0 " alt="">
                                    </a>
                                    <div class="flex-1">
                                        <a href="{% url "core:group_inbox_detail" group.slug %}" class="text-base font-semibold capitalize"> {{ group.name }}  </a>
                                        <div class="text-sm text-gray-500 mt-0.5"> {{ group.members.all.count }}  Following</div>
                                    </div>
                                </div>
                            {% endfor %}
                            
                            </div>
                        </div>
                      

                    </div>
                </div>

            </div>
        </div>
        
    </div>



    <!-- open chat box -->
    {% include "partials/chats_dropdown.html" %}
    <!-- open chat box end-->

    <!-- Craete post modal -->
    <div id="create-post-modal" class="create-post" uk-modal>
        <div
            class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical rounded-lg p-0 lg:w-5/12 relative shadow-2xl uk-animation-slide-bottom-small">

            {{group_posts.errors}}
            <form id="group-post-form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="text-center py-4 border-b">
                    <h3 class="text-lg font-semibold"> Create Post </h3>
                    <button class="uk-modal-close-default bg-gray-100 rounded-full p-2.5 m-1 right-2" type="button" uk-close uk-tooltip="title: Close ; pos: bottom ;offset:7"></button>
                </div>
                <div class="flex flex-1 items-start space-x-4 p-5">
                    <img src="{{ request.user.profile.image.url }}"
                        class="bg-gray-200 border border-white rounded-full w-11 h-11">
                    <div class="flex-1 pt-2">
                        <textarea name="group-post-caption" id="group-post-caption" class="uk-textare text-black shadow-none focus:shadow-none text-xl font-medium resize-none" rows="5"
                            placeholder="What's on your mind {{request.user|title}}?"></textarea>
                    </div>
        
                </div>

                <div class="flex flex-1 p-5 w-100">
                    <div class="flex-1 pt-2">
                        <img src="https://www.survivorsuk.org/wp-content/uploads/2017/01/no-image.jpg" id="preview_group_post_thumbnail" style="width: 100%; height: 200px; object-fit: cover; border-redius: 10px;" alt="" for="group-post-thumbnail">
                    </div>
                </div>

                <div class="bsolute bottom-0 p-4 space-x-4 w-full">
                    <div class="flex bg-gray-50 border border-purple-100 rounded-2xl p-2 shadow-sm items-center">
                        <div class="lg:block hidden ml-1"> Add to your post </div>
                        <div class="flex flex-1 items-center lg:justify-end justify-center space-x-2">

                            <label for="group-post-thumbnail" class="m-0">
                                <svg class="bg-blue-100 h-9 p-1.5 rounded-full text-blue-600 w-9 cursor-pointer" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                            </label>
                            <input onchange="loadFile(event)" type="file" class="d-none" name="group-post-thumbnail" id="group-post-thumbnail">
                        </div>
                    </div>
                </div>
                

                <div class="flex items-center w-full justify-between p-3 border-t">
        
                    <select class="selectpicker mt-2 story" id="group-post-visibility" name="group-post-visibility">
                        <option value="Everyone">Everyone</option>
                        <option value="Only me">Only me</option>
                    </select>
        
                    <div class="flex space-x-2">
                        <button type="submit" class="bg-blue-600 flex h-9 items-center justify-center rounded-md text-white px-5 font-medium">
                        Share </button>   
                        <input type="hidden" name="group_id" id="group_id" value="{{ group.id }}"> 
                    </div>

                    <a href="#" hidden
                        class="bg-blue-600 flex h-9 items-center justify-center rounded-lg text-white px-12 font-semibold">
                        Share </a>
                </div>
            </form>
        </div>
    </div>

    <script>
        var loadFile = function(event){
            var output2 = document.getElementById("preview_group_post_thumbnail")
            output2.src = URL.createObjectURL(event.target.files[0])
            output2.onload = function(){
                URL.revokeObjectURL(output2.src)
            }
        }
    </script>
    
    

{% endblock content %}

templates/core/photos.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}

<!-- Main Contents -->
<div class="main_content">
    <div class="mcontainer">


        <div class="flex justify-between items-center relative md:mb-4 mb-3">
            <div class="flex-1">
                <h2 class="text-2xl font-semibold"> Photos </h2>
                <nav class="responsive-nav border-b md:m-0 -mx-4">
                    <ul>
                        <li class="active"><a href="#" class="lg:px-2">  Photos of you </a></li>
                    </ul>
                </nav>
            </div>
        </div>

        <div class="grid md:grid-cols-4 grid-cols-2 gap-3 mt-5">
            {% for post in posts %}
                {% if post.image %}
                    <div>
                        <div class="bg-green-400 max-w-full lg:h-56 h-48 rounded-lg relative overflow-hidden shadow uk-transition-toggle">
                            <img src="{{ post.image.url }}" class="w-full h-full absolute object-cover inset-0">
                            <!-- overly-->
                            <div class="-bottom-12 absolute bg-gradient-to-b from-transparent h-1/2 to-gray-800 uk-transition-slide-bottom-small w-full"></div>
                            <div class="absolute bottom-0 w-full p-3 text-white uk-transition-slide-bottom-small flex items-center">
                                <div class="flex-1">
                                    <div class="text-lg"> {{ post.title }} </div>
                                    <div class="flex space-x-3 lg:flex-initial text-sm">
                                        <a href="#">  Like</a>
                                        <a href="#">  Comment </a>
                                        <a href="#">  Share </a>
                                    </div>
                                </div>
                                <a href="{{ post.image.url }}" download="{{ post.image.url }}" class="btn-down text-2xl uil-cloud-download px-1"></a>
                                
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            
        </div>


    </div>
</div>

</div>
{% endblock content %}