base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),

    # Web Socket
    path("ws/", include(websocket_urlpatterns)),

    # Change Password
    path('user/change-password/', auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',
         success_url='/user/password-reset-complete/'), name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path('reset_password/', auth_views.PasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.RegisterView, name='sign-up'),
    path('sign-in/', views.LoginView, name='sign-in'),
    path('logout/', views.LogoutView, name='logout'),

    path('my-profile/', views.my_profile, name='my-profile'),
    path('profile/<username>', views.friend_profile, name='profile'),

    path("profile-update/", views.profile_update, name="profile-update"),
    path("delete-user/", views.delete_user, name="delete-user"),

    # Tabs
    path("friends-tab/", views.friends_tab, name="friends-tab"),

]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.utils.text import slugify
from PIL import Image
from shortuuid.django_fields import ShortUUIDField
import shortuuid

RELATIONSHIP = (
    ('Single', 'Single'),
    ('Married', 'Married'),
    ('In love', 'In love')
)

GENDER = (
    ('male', 'Male'),
    ('female', 'Female')
)

WHO_CAN_SEE_MY_FRIENDS = (
    ("Only Me", "Only Me"),
    ("Everyone", "Everyone"),
)


def user_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (instance.user.id, ext),
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class User(AbstractUser):
    full_name = models.CharField(max_length=200)
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=200)
    gender = models.CharField(max_length=100, choices=GENDER, default='male')

    otp = models.CharField(max_length=10, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class Profile(models.Model):
    PID = ShortUUIDField(length=7, max_length=25,
                         alphabet='abcdefghijklmnopqrstuvwxyz')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image = models.ImageField(
        upload_to=user_directory_path, blank=True, null=True, default='cover.jpg')
    image = models.ImageField(
        upload_to=user_directory_path, blank=True, null=True, default='default.jpg')
    full_name = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, default='Male')
    relationship = models.CharField(
        max_length=100, choices=RELATIONSHIP, default='Single')
    friends_visibility = models.CharField(
        max_length=100, choices=WHO_CAN_SEE_MY_FRIENDS, null=True, blank=True, default="Everyone")
    bio = models.CharField(max_length=200, null=True, blank=True)
    about_me = models.TextField(null=True, blank=True)

    country = models.CharField(max_length=200, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)

    working_at = models.CharField(max_length=200, null=True, blank=True)

    instagram = models.CharField(max_length=200, null=True, blank=True)
    whatsapp = models.CharField(max_length=200, null=True, blank=True)
    telegram = models.CharField(max_length=200, null=True, blank=True)

    verified = models.BooleanField(default=False)

    followers = models.ManyToManyField(
        User, blank=True, related_name='followers')
    followings = models.ManyToManyField(
        User, blank=True, related_name='following')
    friends = models.ManyToManyField(
        User, blank=True, related_name='friends')
    blocked = models.ManyToManyField(
        User, blank=True, related_name='blocked')

    groups = models.ManyToManyField(
        "core.Group", blank=True, related_name="groups")
    pages = models.ManyToManyField(
        "core.Page", blank=True, related_name="pages")

    date = models.DateTimeField(auto_now_add=True)

    slug = models.SlugField(unique=True, blank=True, null=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        if self.full_name:
            return str(self.full_name)
        else:
            return str(self.user.username)

    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key = shortuuid.uuid()
            uniqueid = uuid_key[:2]
            self.slug = slugify(self.full_name) + '-' + str(uniqueid.lower())
        super(Profile, self).save(*args, **kwargs)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import PasswordResetForm
from django.forms import ImageField, FileInput

from userauths.models import User, Profile


class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(
        attrs={"placeholder": "Full Name"}))
    username = forms.CharField(widget=forms.TextInput(
        attrs={"placeholder": "Username"}))
    phone = forms.CharField(widget=forms.TextInput(
        attrs={"placeholder": "Mobile No."}))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={"placeholder": "Email Address"}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={"placeholder": "Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={"placeholder": "Confirm Password"}))

    class Meta:
        model = User
        fields = ['full_name', 'username', 'email',
                  'phone', 'gender', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = "with-border"


class ProfileUpdateForm(forms.ModelForm):
    image = ImageField(widget=FileInput)

    class Meta:
        model = Profile
        fields = [
            'cover_image',
            'image',
            'full_name',
            'bio',
            'about_me',
            'phone',
            'gender',
            'relationship',
            'friends_visibility',
            'country',
            'city',
            'state',
            'address',
            'working_at',
            'instagram',
            'whatsapp',
        ]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=254, label='Email', widget=forms.EmailInput(
        attrs={'autocomplete': 'email'}))

userauths/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string

from core.models import Group, GroupChat, Post, FriendRequest
from userauths.forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from userauths.models import Profile, User


def RegisterView(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already registered!")
        return redirect("core:feed")

    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        full_name = form.cleaned_data.get("full_name")
        phone = form.cleaned_data.get("phone")
        gender = form.cleaned_data.get("gender")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")

        user = authenticate(email=email, password=password)
        login(request, user)

        profile = Profile.objects.get(user=request.user)
        profile.full_name = full_name
        profile.phone = phone
        profile.gender = gender
        profile.save()

        messages.success(
            request, f"Hi! {full_name}! Your account was created successfully.")
        return redirect("core:feed")

    context = {
        "form": form
    }
    return render(request, "userauths/sign-up.html", context)


def LoginView(request):

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "You are logged In!")
                return redirect("core:feed")
            else:
                messages.error(request, "Username or password does not match")
                return redirect("userauths:sign-up")
        except:
            messages.error(request, "Username does not exist")
            return redirect("userauths:sign-up")

    return HttpResponseRedirect("/")


def LogoutView(request):
    logout(request)
    messages.success(request, "You are logged out!")
    return redirect("userauths:sign-up")


@login_required
def my_profile(request):
    profile = request.user.profile
    posts = Post.objects.filter(active=True, user=request.user).order_by("-id")
    groups = Group.objects.filter(
        active=True).order_by("-id")

    groupchat = GroupChat.objects.filter(
        members=request.user, active=True)

    context = {
        "profile": profile,
        "posts": posts,
        "groups": groups,
        "groupchat": groupchat,
    }
    return render(request, "userauths/my-profile.html", context)


@login_required
def profile_update(request):
    print("Handling profile update request...")

    if request.method == "POST":
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        user_form = UserUpdateForm(request.POST, instance=request.user)

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()

            messages.success(request, "Profile Updated Successfully.")
            return redirect('userauths:profile-update')
    else:
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        user_form = UserUpdateForm(instance=request.user)

        print("POST request received.")

    context = {
        'profile_form': profile_form,
        'user_form': user_form,
    }
    return render(request, 'userauths/profile-update.html', context)


@login_required
def delete_user(request):
    if request.method == 'POST':
        confirm_delete = request.POST.get('confirm_delete')
        if confirm_delete == 'True':
            # Удалить профиль пользователя
            user = request.user
            user.delete()
            messages.success(request, 'Your profile has been deleted.')
            # Измените URL на тот, который вы хотите использовать после удаления профиля
            return redirect('userauths:sign-up')
        else:
            # Вернуться на страницу обновления профиля, если пользователь нажал "Нет"
            return redirect('userauths:profile-update')
    else:
        # Если запрос не POST, перенаправить на страницу обновления профиля
        return render(request, 'userauths/delete-user.html')


@login_required
def friend_profile(request, username):
    profile = Profile.objects.get(user__username=username)
    if request.user.profile == profile:
        return redirect("userauths:my-profile")

    user = profile.user
    friend_groups = Group.objects.filter(members=user)
    unique_groups = set(friend_groups)

    groupchat = GroupChat.objects.filter(
        members=request.user, active=True)

    posts = Post.objects.filter(active=True, user=profile.user).order_by("-id")

    bool = False
    bool_friend = False

    sender = request.user
    receiver = profile.user

    try:
        friend_request = FriendRequest.objects.filter(
            sender=sender, receiver=receiver)
        if friend_request:
            bool = True
        else:
            bool = False
    except:
        bool = False

    context = {
        "profile": profile,
        "posts": posts,
        "bool": bool,
        "bool_friend": bool_friend,
        "groups": unique_groups,
        "groupchat": groupchat,
    }
    return render(request, "userauths/friend-profile.html", context)


@login_required
def friends_tab(request):
    # Получить текущий URL
    current_url = request.get_full_path()

    # Проверить, является ли текущий URL страницей профиля пользователя
    if "/user/my-profile/" in current_url:
        # Если да, то перенаправить на вкладку "Друзья" в профиле пользователя
        return redirect("userauths:my-profile") + "friends-tab/"

    # Проверить, является ли текущий URL страницей профиля друга
    elif "/user/profile/" in current_url:
        # Если да, то извлечь имя пользователя из URL
        username = current_url.split("/user/profile/")[1].split("/")[0]
        # Перенаправить на вкладку "Друзья" в профиле друга
        return redirect("userauths:friend-profile", username=username) + "friends-tab/"
    else:
        # Вернуться на главную страницу, если текущий URL не содержит информацию о профиле пользователя или друга
        return redirect("core:feed")

templates/userauths/delete-user.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

<style>
    #id_new_password1{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
        
    }
    #id_new_password2{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }

    #id_old_password{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }

    .btn-container {
        text-align: center;
    }
    .btn {
        display: inline-block;
        margin: 0 10px;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }
    .btn-yes {
        background-color: #dc3545;
        color: white;
    }
    .btn-no {
        background-color: #6c757d;
        color: white;
    }
</style>

<div class="main_content">
    <div class="mcontainer">
        <div class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4">
            {% include 'partials/settings_sidebar.html' %}
            <div class="lg:w-2/3">
                <div class="lg:flex lg:flex-col justify-between lg:h-full">
                    <div class="lg:px-10 lg:py-8 p-6">
                        <h3 class="font-bold mb-2 text-xl text-center">Are you sure you want to delete your account?</h3>
                        <form method="POST" action="{% url 'userauths:delete-user' %}">
                            {% csrf_token %}
                            <input type="hidden" name="confirm_delete" value="True">
                            <div class="btn-container">
                                <button type="submit" class="btn btn-yes">Yes</button>
                                <button type="button" class="btn btn-no" onclick="window.location.href='{% url 'userauths:profile-update' %}'">No</button>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/userauths/profile-update.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

        <style>
            
            #id_image{
                background-color: #270041;
                border-radius: 4px;
                height: 50px;
                width: 100%;
                color: #ffffff;
            }
            #id_image::file-selector-button{
                border: none;
                border-radius: 7px;
                color: 432f9f;
                background-color: #ffffff;
                height: 30px;
                cursor: pointer;
                transition: all .25s ease-in;
                margin-top: 1px;
                margin-left: 10px;
            }
        </style>


        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <div class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4">
                    
                    {% include 'partials/settings_sidebar.html' %}
                    <div class="lg:w-2/3">

                        
                        {{ user_form.errors }}
                        {{ profile_form.errors }}
                        <form method="POST" class="lg:flex lg:flex-col justify-between lg:h-full" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- form header -->
                            <div class="lg:px-10 lg:py-8 p-6">
                                <h3 class="font-bold mb-2 text-xl">Profile</h3>
                                <p class=""> This information will be dispalyed publicly so be carful what you share. </p>
                            </div>

                            <!-- form body -->
                            <div class="lg:py-8 lg:px-20 flex-1 space-y-4 p-6">

                                

                                <h4><b>Personal</b></h4>
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <!-- Column 1: Profile Image -->
                                    <div class="bg-gray-100 p-4  flex items-center" style="border-radius: 10px;">
                                        <div class="relative">
                                            <img src="{{request.user.profile.image.url}}" id="preview_avatar" alt="Profile Picture" class="w-24 h-24 rounded-full">
                                            <label for="id_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                                <i class="fas fa-pen text-blue-500"></i>
                                            </label>
                                        </div>
                                    </div>


                                    <!-- Column 2: Cover Image -->
                                    <div class="bg-blue-100 p-4" style="border-radius: 10px;">
                                        <div class="relative">
                                        <img src="{{request.user.profile.cover_image.url}}" id="preview_cover" alt="Cover Image" class="w-full h-32 object-cover rounded-lg">
                                        <label for="id_cover_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                            <i class="fas fa-pen text-blue-500"></i>
                                        </label>
                                        </div>
                                    </div>

                                    <script>
                                        var loadFile = function (event) {
                                          var output2 = document.getElementById("preview_avatar");
                                          output2.src = URL.createObjectURL(event.target.files[0]);
                                          output2.onload = function () {
                                            URL.revokeObjectURL(output2.src); // free memory
                                          };
                                        };

                                        var loadFile2 = function (event) {
                                          var output2 = document.getElementById("preview_cover");
                                          output2.src = URL.createObjectURL(event.target.files[0]);
                                          output2.onload = function () {
                                            URL.revokeObjectURL(output2.src); // free memory
                                          };
                                        };
                                      </script>

                                </div>
                                <div class="d-none">
                                    <div class="line">
                                        {% render_field profile_form.image onchange="loadFile(event)" class="hidden"  %}
                                    </div>
                                    <div class="line">
                                        {% render_field profile_form.cover_image onchange="loadFile2(event)" class="hidden"  %}
                                    </div>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.full_name class="line__input" %}
                                    <span for="username" class="line__placeholder"> First Name   </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.bio class="line__input"  %}
                                    <span for="username" class="line__placeholder"> Bio  </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.gender class="line__input" %}
                                    <span for="username" class="line__placeholder"> Gender   </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.relationship class="line__input" %}
                                    <span for="username" class="line__placeholder"> Relationship Status   </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.about_me class="line__input" %}
                                    <span for="username" class="line__placeholder"> About me   </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6" style="padding-top:80px;">
                                <h4><b>Contact</b></h4>
                                <div class="line">
                                    {% render_field profile_form.phone class="line__input" %}
                                    <span for="username" class="line__placeholder"> Mobile Number   </span>
                                </div>
                                <div class="line">
                                    {% render_field user_form.email class="line__input" %}
                                    <span for="username" class="line__placeholder"> Email  </span>
                                </div>
                            </div>


                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Address</b></h4>
                                <div class="line">
                                    {% render_field profile_form.address class="line__input" %}
                                    <span for="username" class="line__placeholder"> Address   </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.city class="line__input" %}
                                    <span for="username" class="line__placeholder"> City  </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.state class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.country class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Socila URLs</b></h4>
                                <div class="line">
                                    {% render_field profile_form.instagram class="line__input" %}
                                    <span for="username" class="line__placeholder"> Instagram   </span>
                                </div>
                                <div class="line">
                                    {% render_field profile_form.whatsApp class="line__input" %}
                                    <span for="username" class="line__placeholder"> WhatsApp  </span>
                                </div>
                            </div>

                            <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                                <button type="submit" class="button bg-blue-700"> Save Changes </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}