base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),

    # Web Socket
    path("ws/", include(websocket_urlpatterns)),

    # Change Password
    path('user/change-password/', auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',
         success_url='/user/password-reset-complete/'), name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path('reset_password/', auth_views.PasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='feed'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('groups/', views.groups, name='groups'),
    path('create-group/', views.create_group, name='create-group'),
    path('group-index/<slug:slug>/', views.group_index, name='group-index'),
    path('join-group/<slug:slug>/', views.join_group, name='join-group'),
    path('unfollow-group/<slug:slug>/',
         views.unfollow_group, name='unfollow-group'),
    path('photos/', views.photos, name='photos'),

    # Chat
    path('core/inbox/', views.inbox, name='inbox'),
    path('core/inbox/<username>/', views.inbox_detail, name='inbox_detail'),

    # Group Chat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/create-groupchat/", views.create_groupchat, name="create-groupchat"),
    path("core/group-inbox/<slug:slug>/",
         views.group_inbox_detail, name="group_inbox_detail"),

    # Join & leave Group Chat
    path("core/join-group-page/<slug:slug>/",
         views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/",
         views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/",
         views.leave_group_chat, name="leave_group_chat"),

    # Search
    path('search/', views.search_users, name='search_users'),

    # Games
    path("all-games/", views.games, name="games"),
    path("stack_brick/", views.stack_brick, name="stack_brick"),
    path("snake/", views.snake, name="snake"),

    # Load more post
    path('load_more_posts/', views.load_more_posts, name='load_more_posts'),




    # Ajax URLs
    path('create-post/', views.create_post, name='create-post'),
    path('like-post/', views.like_post, name='like-post'),
    path('comment-post/', views.comment_on_post, name='comment-post'),
    path('delete-post/', views.delete_post, name='delete-post'),
    path('like-comment/', views.like_comment, name='like-comment'),
    path('reply-comment/', views.reply_comment, name='reply-comment'),
    path('delete-comment/', views.delete_comment, name='delete-comment'),
    path('delete-reply/', views.delete_reply, name='delete-reply'),

    path('create-group-post/', views.create_group_post, name='create-group-post'),
    path('like-group-post/', views.like_group_post, name='like-group-post'),
    path('comment-group-post/', views.comment_on_group_post,
         name='comment-group-post'),
    path('delete-group-post/', views.delete_group_post, name='delete-group-post'),
    path('like-group-post-comment/', views.like_group_post_comment,
         name='like-group-post-comment'),
    path('reply-group-post-comment/', views.reply_group_post_comment,
         name='reply-group-post-comment'),
    path('delete-group-post-comment/', views.delete_group_post_comment,
         name='delete-group-post-comment'),
    path('delete-group-post-reply/', views.delete_group_post_reply,
         name='delete-group-post-reply'),

    path('add-friend/', views.add_friend, name='add-friend'),
    path('unfriend/', views.unfriend, name='unfriend'),
    path('accept-friend-request/', views.accept_friend_request,
         name='accept-friend-request'),
    path('reject-friend-request/', views.reject_friend_request,
         name='reject-friend-request'),
    path('block-user/', views.block_user, name='block-user'),
    path('update-notification/', views.update_notification_status,
         name='update-notification'),
    path('mark-as-read-all/', views.mark_as_read_all, name='mark-as-read-all'),

    path('create-group-post/', views.create_group_post, name='create-group-post'),

]

templates/chat/create-groupchat.html
{% extends "partials/base.html" %}
{% load static %}
{% load widget_tweaks  %}

{% block content %}

        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <!--  breadcrumb -->
                <div class="breadcrumb-area py-0">
                    <div class="breadcrumb">
                        <ul class="m-0">
                            <li>
                                <a href="{% url "core:group_inbox" %}">Group Messages</a>
                            </li>
                            <li class="active">
                                <a href="#">Create New Group Chat </a>
                            </li>
                        </ul>
                    </div>
                </div>


                <!-- create page-->
                <div class="max-w-2xl m-auto shadow-md rounded-md bg-white lg:mt-20">  
 
                    <!-- form header -->
                    <div class="text-center border-b border-gray-100 py-6">
                        <h3 class="font-bold text-xl"> Create New Group Chat </h3>
                    </div>

                    <!-- form body -->
                    {{form.errors}}
                    <form method="POST" action="{% url 'core:create-groupchat' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="p-10 space-y-7">
                            <div class="line">
                                <input class="line__input" id="groupchat-caption" name="groupchat-caption" type="text" onkeyup="this.setAttribute('value', this.value);" value="" autocomplete="off">
                                <span for="username" class="line__placeholder"> Groupchat Name </span>
                            </div>
                            
                            <div class="line h-32"> 
                                <textarea class="line__input h-32"  id="groupchat-description" name="groupchat-description" type="text" onkeyup="this.setAttribute('value', this.value);" value="" autocomplete="off"></textarea>
                                <span for="username" class="line__placeholder"> Groupchat description </span> 
                            </div>

                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <!-- Group Image -->
                                <div class="bg-gray-100 p-4  flex items-center" style="border-radius: 10px;">
                                    <div class="relative">
                                        <img src="{% static 'assets/images/group/noimage.gif' %}" id="preview_avatar" alt="Group Image" class="w-24 h-24 rounded-full">
                                        <label for="groupchat-thumbnail" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                            <i class="fas fa-pen text-blue-500"></i>
                                        </label>
                                    </div>
                                </div>

                                <input type="file" name="groupchat-thumbnail" id="groupchat-thumbnail" onchange="loadFile(event)" style="display: none;">
                                <script>
                                    var loadFile = function (event) {
                                      var output2 = document.getElementById("preview_avatar");
                                      output2.src = URL.createObjectURL(event.target.files[0]);
                                      output2.onload = function () {
                                        URL.revokeObjectURL(output2.src); // free memory
                                      };
                                    };
                                </script>
                            </div>
                        </div>
                        
                        <!-- form footer -->
                        <div class="flex justify-center border-gray-100 py-8">
                            <button type="submit" class="button lg:w-1/3">
                                Create
                            </button>
                        </div>
                        
                    </form>
                </div>

            </div>
        </div>
        
    </div>



    
    <!-- open chat box -->
    {% include "partials/chats_dropdown.html" %}    
    <!-- open chat box -->

    
{% endblock content %}

templates/chat/group_inbox.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

    <!-- Main Contents -->
    <div class="main_content">

        <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

        <div class="messages-container">
            <div class="messages-container-inner">


                <div class="messages-inbox">
                    <div class="messages-headline">
                        <div class="input-with-icon" hidden>
                            <input id="autocomplete-input" type="text" placeholder="Search">
                            <i class="icon-material-outline-search"></i>
                        </div>
                        <h2 class="text-2xl font-semibold">Chats</h2>
                        <a href="{% url 'core:create-groupchat' %}" class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></a>
                    </div>
                    <div class="messages-inbox-inner" data-simplebar>
                        <ul>
                            
                            {% for message in groupchat %}
                                <li>
                                    <a href="{% url 'core:group_inbox_detail' message.slug %}">
                                        <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{message.images.url}}" alt=""></div>

                                        <div class="message-by">
                                            <div class="message-by-headline">
                                                <h5>{{message.name}}</h5>
                                            </div>
                                            <p>{{message.last_message.message|truncatechars:40}}</p>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>


                <div class="message-content">

                    <div class="messages-headline">
                        <h4> All My Group Chats </h4>
                    </div>

                    <div class="message-content-scrolbar" data-simplebar>
                        <div class="message-content-inner">
                            <div class="card md:p-6 p-2 max-w-3xl mx-auto">
                                <div class="grid md:grid-cols-2  grid-cols-2 gap-x-2 gap-y-4 mt-3">
                                    
                                    {% for message in groupchat %}
                                        <div class="flex items-center flex-col md:flex-row justify-center p-4 rounded-md shadow hover:shadow-md md:space-x-4">
                                            <a href="timeline-group.html" iv="" class="w-16 h-16 flex-shrink-0 overflow-hidden rounded-full relative">
                                                <img src="{{message.images.url}}" class="absolute w-full h-full inset-0 " alt="">
                                            </a>
                                            <div class="flex-4">
                                                <a href="timeline-page.html" class="text-base font-semibold capitalize">{{message.name}} </a>
                                                <div class="text-sm text-gray-500"> {{message.members.all.count}} Members</div>
                                            </div>
                                            <a href="{% url 'core:group_inbox_detail' message.slug %}" class="bg-blue-500 text-white text-center font-semibold py-2 px-3 rounded-md text-sm md:mt-0 mt-3">Join Conversation</a>
                                        </div>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- open chat box -->
    {% include "partials/chats_dropdown.html" %}
    <!-- open chat box end-->

    {% endblock content %}

templates/chat/group_inbox_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

    <!-- Main Contents -->
    <div class="main_content">

        <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

        <div class="messages-container">
            <div class="messages-container-inner">


                <div class="messages-inbox">
                    <div class="messages-headline">
                        <div class="input-with-icon" hidden>
                            <input id="autocomplete-input" type="text" placeholder="Search">
                            <i class="icon-material-outline-search"></i>
                        </div>
                        <h2 class="text-2xl font-semibold">Chats</h2>
                        <a href="{% url 'core:create-groupchat' %}" class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></a>
                    </div>
                    <div class="messages-inbox-inner" data-simplebar>
                        <ul>
                            
                            {% for message in groupchat_list %}
                                <li>
                                    <a href="{% url 'core:group_inbox_detail' message.slug %}">
                                        <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{message.images.url}}" alt=""></div>

                                        <div class="message-by">
                                            <div class="message-by-headline">
                                                <h5>{{message.name}}</h5>
                                            </div>
                                            <p>{{message.last_message.message|truncatechars:40}}</p>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>


                <div class="message-content">

                    <div class="messages-headline">
                        <div class="flex">
                            <img class="mr-1" src="{{ groupchat.images.url }}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;" alt="">
                            <div>
                                <h4 class="ml-1"> {{ groupchat.name }} </h4>
                                <p style="font-size: 13px; margin-top: -12px;">{{groupchat.members.all.count}} Members</p>
                            </div>
                        </div>
                        <a href="{% url 'core:leave_group_chat' groupchat.slug  %}" class="message-action text-red-500"><i class="fas fa-sign-out-alt"></i> <span class="md:inline hidden">Leave Group</span> </a>
                    </div>

                    <div class="message-content-scrolbar" data-simplebar>

                        <!-- Message Content Inner -->
                        <div class="message-content-inner chat_container" style="overflow-y: scroll; max-height: 550px; height: auto; ">

                            <!-- Time Sign -->
                            <div class="message-time-sign">
                                <span>Created on {{groupchat.date|date:"d M, Y"}}</span>
                            </div>

                            
                            {% for message in group_messages %}
                            
                                {% if message.sender == request.user %}
                                    <div class="message-bubble me">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ message.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{message.message}}</p>
                                                <p style="color: rgba(255, 255, 255, 0.479);"><small>{{ message.date|timesince }} ago - {{ message.sender.profile.full_name }}</small></p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% else %}
                                    <div class="message-bubble">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ message.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{message.message}}</p>
                                                <p style="color: gray"><small>{{ message.date|timesince }} ago - {{ message.sender.profile.full_name }}</small></p>

                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div id="chat-messages"></div>

                        </div>

                        <!-- Reply Area -->
                        <div class="message-reply">
                            <textarea id="chat-input" cols="1" rows="1" placeholder="Write Message"></textarea>
                            <button id="send-btn" class="button ripple-effect" >Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(function() {
            var group_name = "{{group_name}}";
            var groupchat_id = "{{groupchat.id}}";

            console.log(group_name);
            console.log(groupchat_id);
    
            var socket = new WebSocket('ws://' + window.location.host + '/ws/group-chat/' + group_name + '/');
    
            socket.onopen = function() {
                console.log('WebSocket connection established.');
            }
    
            socket.onmessage = function(event) {
                console.log(event);
                var data = JSON.parse(event.data);
                var message = data.message;
                var sender = data.sender;
                var profileImage = data.profile_image;
                var groupchat_id = data.groupchat_id;
                var full_name = data.full_name
                var date = data.date
     
                if (sender === "{{request.user}}") {
                        var chatMessage = '<div class="message-bubble me">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '<p style="color: rgba(255, 255, 255, 0.479);"><small>' + date + ' ago - ' + full_name + '</small></p>'

                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        // Append the chat message to the main div
                        $('#chat-messages').append(chatMessage);
                        // Get the chat container
                        var chatContainer = document.querySelector('.chat_container');
                        // Automatically scroll to the bottom of the message after sending.
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                } else {
                    var chatMessage = '<div class="message-bubble">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '<p style="color: gray"><small>' + date + ' ago - ' + full_name + '</small></p>'
                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        $('#chat-messages').append(chatMessage);

                        var chatContainer = document.querySelector('.chat_container');
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                        console.log("No");
                }
            }
    
            socket.onclose = function() {
                console.log('WebSocket connection closed.');
            }
    
            $('#send-btn').on('click', function() {
                var input = $('#chat-input');
                var message = input.val();
                var sender = "{{request.user.username}}"; 
                var data = {
                    'message': message,
                    'sender': sender,
                    'groupchat_id': 1,
                };
                socket.send(JSON.stringify(data));
                input.val('');
                var sendButton = $('#send-btn');
                sendButton.prop('disabled', true);
                $(".chat_container").scrollTop(100000000000);
            });
    
        });


       


        $(document).ready(function() {
          $(".chat_container").scrollTop(100000000000);
        });

    </script>

    <script>
       $(document).ready(function() {
            var chatInputValue = $('#chat-input');
            var sendButton = $('#send-btn');

            // Disable the button initially
            sendButton.prop('disabled', true);

            // Check input field on keyup event
            chatInputValue.on('keyup', function() {
                var inputText = $(this).val();

                // Enable/disable button based on input field value
                if (inputText.trim() !== '') {
                    sendButton.prop('disabled', false);
                } else {
                    sendButton.prop('disabled', true);
                }
            });
        })
    </script>


    

    {% endblock content %}

templates/chat/inbox.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}

        <!-- Main Contents -->
        <div class="main_content">

            <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

            <div class="messages-container">
                <div class="messages-container-inner">


                    <div class="messages-inbox">
                        <div class="messages-headline">
                            <div class="input-with-icon" hidden>
                                <input id="autocomplete-input" type="text" placeholder="Search">
                                <i class="icon-material-outline-search"></i>
                            </div>
                            <h2 class="text-2xl font-semibold">Chats</h2>
                            <span class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></span>
                        </div>
                        <div class="messages-inbox-inner" data-simplebar>
                            <ul>
                                {% for message in chat_message %}
                                    {% if request.user == message.sender %}
                                        <li>
                                            <a href="{% url "core:inbox_detail" message.receiver.username %}">
                                                <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{ message.receiver.profile.image.url }}" alt=""></div>

                                                <div class="message-by">
                                                    <div class="message-by-headline">
                                                        <h5>{{ message.receiver.profile.full_name }}</h5>
                                                        <span style="font-size:12px"> <small>{{ message.date|timesince }} ago</small></span>
                                                    </div>
                                                    <p>{{ message.message }}</p>
                                                </div>
                                            </a>
                                        </li>
                                    {% endif %}
                                  
                                    {% if request.user == message.receiver %}
                                        <li>
                                            <a href="{% url "core:inbox_detail" message.sender.username %}">
                                                <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{ message.sender.profile.image.url }}" alt=""></div>

                                                <div class="message-by">
                                                    <div class="message-by-headline">
                                                        <h5>{{ message.sender.profile.full_name }}</h5>
                                                        <span style="font-size:12px"> <small>{{ message.date|timesince }} ago</small></span>
                                                    </div>
                                                    <p>{{ message.message }}</p>
                                                </div>
                                            </a>
                                        </li>
                                    {% endif %}

                                {% empty %}
                                    <li>
                                        <a href="#">

                                            <div class="message-by">
                                                <div class="message-by-headline">
                                                    <h5>No messages yet</h5>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>


                    <div class="message-content">

                        <div class="messages-headline">
                            <h4> Start a new conversation </h4>
                            <a href="#" class="message-action text-red-500"><i class="icon-feather-trash-2"></i> <span class="md:inline hidden"> Delete Conversation</span> </a>
                        </div>

                        <div class="message-content-scrolbar" data-simplebar>

                            <!-- Message Content Inner -->
                            <div class="message-content-inner">

                                
                            </div>
                            <!-- Message Content Inner / End -->

                            <!-- Reply Area -->
                            <div class="message-reply">
                                <textarea cols="1" rows="1" placeholder="Your Message"></textarea>
                                <button class="button ripple-effect">Send</button>
                            </div>

                        </div>

                    </div>


                </div>
            </div>

        </div>

    </div>



    <!-- open chat box -->
    {% include "partials/chats_dropdown.html" %}
    <!-- open chat box end-->


    
{% endblock content %}